# Site settings
title: Abdul Muhyi Bin Faidzuli
email: youremail@example.com
description: ritsumeikan university | robotics major
baseurl: ""
url: "https://Kurumin03.github.io"

# Remote theme setup
remote_theme: yousinix/portfolYOU@v2.3.0
plugins:
  - jekyll-remote-theme

# Navigation weight (optional)
collections:
  projects:
    output: true
  timeline:
    output: true
  education:
    output: true
  intern:
    output: true
  pages:
    output: true
    
# Markdown & permalinks
markdown: kramdown
permalink: pretty

# Data files to include
include:
  - _data

# External links target
external_new_tab: true
